# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bai3_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(382, 304)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 20, 161, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("login_icon.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_USER = QtWidgets.QLineEdit(Form)
        self.lineEdit_USER.setGeometry(QtCore.QRect(120, 120, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_USER.setFont(font)
        self.lineEdit_USER.setObjectName("lineEdit_USER")
        self.lineEdit_PASS = QtWidgets.QLineEdit(Form)
        self.lineEdit_PASS.setGeometry(QtCore.QRect(120, 170, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_PASS.setFont(font)
        self.lineEdit_PASS.setObjectName("lineEdit_PASS")
        self.pushButton_LOGIN = QtWidgets.QPushButton(Form)
        self.pushButton_LOGIN.setGeometry(QtCore.QRect(160, 230, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_LOGIN.setFont(font)
        self.pushButton_LOGIN.setObjectName("pushButton_LOGIN")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "USER"))
        self.label_3.setText(_translate("Form", "PASS"))
        self.pushButton_LOGIN.setText(_translate("Form", "LOGIN"))
