# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_tinh_tong.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 244)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 150, 111, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_a = QtWidgets.QLabel(self.centralwidget)
        self.label_a.setGeometry(QtCore.QRect(70, 30, 21, 21))
        self.label_a.setObjectName("label_a")
        self.lineEdit_inputA = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_inputA.setGeometry(QtCore.QRect(110, 30, 51, 21))
        self.lineEdit_inputA.setObjectName("lineEdit_inputA")
        self.lineEdit_inputB = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_inputB.setGeometry(QtCore.QRect(110, 60, 51, 21))
        self.lineEdit_inputB.setObjectName("lineEdit_inputB")
        self.label_b = QtWidgets.QLabel(self.centralwidget)
        self.label_b.setGeometry(QtCore.QRect(70, 60, 21, 21))
        self.label_b.setObjectName("label_b")
        self.label_tong = QtWidgets.QLabel(self.centralwidget)
        self.label_tong.setGeometry(QtCore.QRect(60, 100, 41, 31))
        self.label_tong.setObjectName("label_tong")
        self.ket_qua = QtWidgets.QLabel(self.centralwidget)
        self.ket_qua.setGeometry(QtCore.QRect(110, 100, 61, 31))
        self.ket_qua.setObjectName("ket_qua")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.sumAB)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TinhTong"))
        self.pushButton.setText(_translate("MainWindow", "Tính tổng"))
        self.label_a.setText(_translate("MainWindow", "a"))
        self.label_b.setText(_translate("MainWindow", "b"))
        self.label_tong.setText(_translate("MainWindow", "Tổng:"))
        self.ket_qua.setText(_translate("MainWindow", "TextLabel"))

    def sumAB(self, MainWindow):
        self.sum = int(self.lineEdit_inputA.text()) + int(self.lineEdit_inputB.text())
        self.ket_qua.setText(str(self.sum))
        self.ket_qua.adjustSize()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
