# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bai1_quan_ly_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets

csdl = sqlite3.connect('taikhoan.db')

dl = csdl.cursor()

dl.execute('''CREATE TABLE IF NOT EXISTS tai_khoan(
    user char[50], pass char[10])''')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(373, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 0, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_USER = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_USER.setGeometry(QtCore.QRect(120, 70, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_USER.setFont(font)
        self.lineEdit_USER.setObjectName("lineEdit_USER")
        self.lineEdit_PASS = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_PASS.setGeometry(QtCore.QRect(120, 130, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_PASS.setFont(font)
        self.lineEdit_PASS.setObjectName("lineEdit_PASS")
        self.pushButton_THEM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_THEM.setGeometry(QtCore.QRect(50, 200, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_THEM.setFont(font)
        self.pushButton_THEM.setObjectName("pushButton_THEM")
        self.pushButton_XOA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_XOA.setGeometry(QtCore.QRect(150, 200, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_XOA.setFont(font)
        self.pushButton_XOA.setObjectName("pushButton_XOA")
        self.pushButton_SUA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SUA.setGeometry(QtCore.QRect(250, 200, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_SUA.setFont(font)
        self.pushButton_SUA.setObjectName("pushButton_SUA")
        self.pushButton_TIMKIEM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_TIMKIEM.setGeometry(QtCore.QRect(70, 270, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_TIMKIEM.setFont(font)
        self.pushButton_TIMKIEM.setObjectName("pushButton_TIMKIEM")
        self.pushButton_XEM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_XEM.setGeometry(QtCore.QRect(200, 270, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_XEM.setFont(font)
        self.pushButton_XEM.setObjectName("pushButton_XEM")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(15, 340, 341, 201))
        self.listView.setObjectName("listView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 373, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #******************************MY CODE HERE*************************************#
        self.pushButton_THEM.clicked.connect(self.add_user)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "QL user"))
        self.label_2.setText(_translate("MainWindow", "USER"))
        self.label_3.setText(_translate("MainWindow", "PASS"))
        self.pushButton_THEM.setText(_translate("MainWindow", "Thêm"))
        self.pushButton_XOA.setText(_translate("MainWindow", "Xóa"))
        self.pushButton_SUA.setText(_translate("MainWindow", "Sửa"))
        self.pushButton_TIMKIEM.setText(_translate("MainWindow", "Tìm kiếm"))
        self.pushButton_XEM.setText(_translate("MainWindow", "Xem"))
    
    def add_user(self):
        str1 = str(self.lineEdit_USER.text())
        str2 = str(self.lineEdit_PASS.text())
        if str1 != "" and str2 != "":
            str_tmp = "INSERT INTO tai_khoan (user,pass) VALUES ('"+str1+"','"+str2+"')"
            dl.execute(str_tmp)
            csdl.commit()
            print('ADD_OK!')
        else:
            print('error!')

    def print_all_user(self):
        cur = dl.execute("SELECT user, pass FROM SINHVIEN")
        for row in cur:
            


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
