# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bai2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(467, 418)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_a = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_a.setGeometry(QtCore.QRect(80, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_a.setFont(font)
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.lineEdit_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_c.setGeometry(QtCore.QRect(80, 110, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_c.setFont(font)
        self.lineEdit_c.setObjectName("lineEdit_c")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_b = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_b.setGeometry(QtCore.QRect(280, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_b.setFont(font)
        self.lineEdit_b.setObjectName("lineEdit_b")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 40, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_d = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_d.setGeometry(QtCore.QRect(280, 110, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_d.setFont(font)
        self.lineEdit_d.setObjectName("lineEdit_d")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 110, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(140, 190, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 260, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 330, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_kq = QtWidgets.QLabel(self.centralwidget)
        self.label_kq.setGeometry(QtCore.QRect(100, 330, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_kq.setFont(font)
        self.label_kq.setObjectName("label_kq")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #***********************
        self.comboBox.addItems(["Tính tổng", "Tính tích", "Tìm max", "Sắp tăng"])

        self.pushButton.clicked.connect(self.tinh)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bài 2"))
        self.label.setText(_translate("MainWindow", "a"))
        self.label_2.setText(_translate("MainWindow", "c"))
        self.label_3.setText(_translate("MainWindow", "b"))
        self.label_4.setText(_translate("MainWindow", "d"))
        self.pushButton.setText(_translate("MainWindow", "Thực hiện"))
        self.label_5.setText(_translate("MainWindow", "Kq:"))
        self.label_kq.setText(_translate("MainWindow", "Kết quả"))
    
    def tinhTong(self):
        self.tong = int(self.lineEdit_a.text()) + int(self.lineEdit_b.text()) + int(self.lineEdit_c.text()) + int(self.lineEdit_d.text())
        self.label_kq.setText(str(self.tong))

    def tinhTich(self):
        self.tich = int(self.lineEdit_a.text()) * int(self.lineEdit_b.text()) * int(self.lineEdit_c.text()) * int(self.lineEdit_d.text())
        self.label_kq.setText(str(self.tich))

    def timMax(self):
        self.mang = [int(self.lineEdit_b.text()), int(self.lineEdit_c.text()), int(self.lineEdit_d.text())]
        self.max = int(self.lineEdit_a.text())
        for i in range(len(self.mang)):
            if self.max < self.mang[i]:
                self.max = self.mang[i]
        self.label_kq.setText("max là " + str(self.max))

    def sapTang(self):
        self.sapxep = [int(self.lineEdit_a.text()), int(self.lineEdit_b.text()), int(self.lineEdit_c.text()), int(self.lineEdit_d.text())]
        self.t = " "
        for i in range(0, 3):
            for j in range(i+1, 4):
                if self.sapxep[i] > self.sapxep[j]:
                    self.tmp = self.sapxep[i]
                    self.sapxep[i] = self.sapxep[j]
                    self.sapxep[j] = self.tmp
        for i in range(0,4):
            self.t = self.t + str(self.sapxep[i]) + " "
        self.label_kq.setText(self.t)

    def tinh(self):
        if self.comboBox.currentText() == "Tính tổng":
            self.tinhTong()
        if self.comboBox.currentText() == "Tính tích":
            self.tinhTich()
        if self.comboBox.currentText() == "Tìm max":
            self.timMax()
        if self.comboBox.currentText() == "Sắp tăng":
            self.sapTang()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
