# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bai3_n.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    numTmp = ""
    numA = 0
    numB = 0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(535, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 140, 395, 331))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 3, 1, 1, 1)
        self.pushButton_out = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_out.setFont(font)
        self.pushButton_out.setObjectName("pushButton_out")
        self.gridLayout.addWidget(self.pushButton_out, 3, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 2, 1, 1)
        self.pushButton_chia = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_chia.setFont(font)
        self.pushButton_chia.setObjectName("pushButton_chia")
        self.gridLayout.addWidget(self.pushButton_chia, 0, 3, 1, 1)
        self.pushButton_nhan = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_nhan.setFont(font)
        self.pushButton_nhan.setObjectName("pushButton_nhan")
        self.gridLayout.addWidget(self.pushButton_nhan, 1, 3, 1, 1)
        self.pushButton_tru = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_tru.setFont(font)
        self.pushButton_tru.setObjectName("pushButton_tru")
        self.gridLayout.addWidget(self.pushButton_tru, 2, 3, 1, 1)
        self.pushButton_cong = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_cong.setFont(font)
        self.pushButton_cong.setObjectName("pushButton_cong")
        self.gridLayout.addWidget(self.pushButton_cong, 3, 3, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 3, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(30, 60, 481, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setLineWidth(0)
        self.lcdNumber.setMidLineWidth(0)
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setDigitCount(9)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 10, 61, 21))
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #********************************************
        self.pushButton_0.clicked.connect(lambda: self.xet_nhan("0"))
        self.pushButton_1.clicked.connect(lambda: self.xet_nhan("1"))
        self.pushButton_2.clicked.connect(lambda: self.xet_nhan("2"))
        self.pushButton_3.clicked.connect(lambda: self.xet_nhan("3"))
        self.pushButton_4.clicked.connect(lambda: self.xet_nhan("4"))

        self.pushButton_5.clicked.connect(lambda: self.xet_nhan("5"))
        self.pushButton_6.clicked.connect(lambda: self.xet_nhan("6"))
        self.pushButton_7.clicked.connect(lambda: self.xet_nhan("7"))
        self.pushButton_8.clicked.connect(lambda: self.xet_nhan("8"))
        self.pushButton_9.clicked.connect(lambda: self.xet_nhan("9"))

        self.pushButton_clear.clicked.connect(lambda: self.xet_nhan("C"))
        self.pushButton_cong.clicked.connect(lambda: self.xet_nhan("+"))
        self.pushButton_tru.clicked.connect(lambda: self.xet_nhan("-"))
        self.pushButton_nhan.clicked.connect(lambda: self.xet_nhan("*"))
        self.pushButton_chia.clicked.connect(lambda: self.xet_nhan("/"))

        self.pushButton_out.clicked.connect(self.out)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bài 3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_out.setText(_translate("MainWindow", "="))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_chia.setText(_translate("MainWindow", "/"))
        self.pushButton_nhan.setText(_translate("MainWindow", "X"))
        self.pushButton_tru.setText(_translate("MainWindow", "-"))
        self.pushButton_cong.setText(_translate("MainWindow", "+"))
        self.pushButton_clear.setText(_translate("MainWindow", "C"))
    
    def xet_nhan(self, c):

        if c == "0":
            self.numTmp = str(self.lcdNumber.intValue()) + "0"
        if c == "1":
            self.numTmp = str(self.lcdNumber.intValue()) + "1"
        if c == "2":
            self.numTmp = str(self.lcdNumber.intValue()) + "2"
        if c == "3":
            self.numTmp = str(self.lcdNumber.intValue()) + "3"
        if c == "4":
            self.numTmp = str(self.lcdNumber.intValue()) + "4"
        if c == "5":
            self.numTmp = str(self.lcdNumber.intValue()) + "5"
        if c == "6":
            self.numTmp = str(self.lcdNumber.intValue()) + "6"
        if c == "7":
            self.numTmp = str(self.lcdNumber.intValue()) + "7"
        if c == "8":
            self.numTmp = str(self.lcdNumber.intValue()) + "8"
        if c == "9":
            self.numTmp = str(self.lcdNumber.intValue()) + "9"
        if c == "C":
            self.numTmp = "0"
            self.numA = 0
            self.numB = 0
            self.label.setText("")
        if c == "+":
            self.numA = self.lcdNumber.intValue()
            self.numTmp = "0"
            self.label.setText("+")
        if c == "-":
            self.numA = self.lcdNumber.intValue()
            self.numTmp = "0"
            self.label.setText("-")
        if c == "*":
            self.numA = self.lcdNumber.intValue()
            self.numTmp = "0"
            self.label.setText("X")
        if c == "/":
            self.numA = self.lcdNumber.intValue()
            self.numTmp = "0"
            self.label.setText("/")

        self.tmp = int(self.numTmp)
        self.lcdNumber.display(self.tmp)

    def out(self):
        self.numB = self.lcdNumber.intValue()
        if self.label.text() == "+":
            self.lcdNumber.display(self.numA + self.numB)
        if self.label.text() == "-":
            self.lcdNumber.display(self.numA - self.numB)
        if self.label.text() == "X":
            self.lcdNumber.display(self.numA * self.numB)
        if self.label.text() == "/":
            self.lcdNumber.display(self.numA / self.numB)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
