# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thread.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread, pyqtSignal
from datetime import datetime, date
import random
import time
import threading
import sqlite3

csdl = sqlite3.connect('thongso.db')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        value = 0
        humi = 0 
        temp = 0
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nhietDo = QtWidgets.QLineEdit(self.centralwidget)
        self.nhietDo.setGeometry(QtCore.QRect(90, 100, 181, 64))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.nhietDo.setFont(font)
        self.nhietDo.setObjectName("nhietDo")
        self.doAm = QtWidgets.QLineEdit(self.centralwidget)
        self.doAm.setGeometry(QtCore.QRect(370, 100, 181, 64))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.doAm.setFont(font)
        self.doAm.setObjectName("doAm")
        self.random_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.random_1.setGeometry(QtCore.QRect(90, 220, 181, 64))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.random_1.setFont(font)
        self.random_1.setObjectName("random_1")
        self.random_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.random_2.setGeometry(QtCore.QRect(370, 220, 181, 64))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.random_2.setFont(font)
        self.random_2.setObjectName("random_2")
        self.ranButton = QtWidgets.QPushButton(self.centralwidget)
        self.ranButton.setGeometry(QtCore.QRect(240, 400, 161, 71))
        self.ranButton.setObjectName("ranButton")
        self.ranButton.clicked.connect(self.ramdomNum)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 100, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 100, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 230, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        t1 = threading.Thread(target = self.random_timer);
        t1.start();
        time.sleep(1) 
        t2 = threading.Thread(target = self.read);
        t2.start();
        time.sleep(1) 


    def random_timer(self):
        while (True):
            value =  str(random.randint(1,1000))
            self.random_2.clear()
            self.random_2.setText(value)
            time.sleep(0.5)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ranButton.setText(_translate("MainWindow", "RANDOM"))
        self.label.setText(_translate("MainWindow", "T"))
        self.label_2.setText(_translate("MainWindow", "H"))
        self.label_3.setText(_translate("MainWindow", "RAN1"))
        self.label_4.setText(_translate("MainWindow", "RAN2"))
    def ramdomNum(self):
        n = random.randint(1,10)
        self.random_1.clear()
        self.random_1.setText(str(n))
    def read(self):
        while (True):
            f = open("thongso.txt","r")
            self.doAm.setText(f.readline())
            self.nhietDo.setText(f.readline())
            temp = self.doAm.text() 
            humid = self.nhietDo.text()
            now = datetime.now()
            today = date.today()
            current_time = now.strftime("%H:%M:%S")
            dates = today.strftime("%d/%m/%Y")
            conn = sqlite3.connect("thongso.db")

            c = conn.cursor()
            # Create table
            c.execute('''CREATE TABLE IF NOT EXISTS thongso
                         (temp text, humid text, date text, time text)''')
            conn.commit()
            c.execute("INSERT INTO thongso VALUES (?,?,?,?)",(temp,humid,dates,current_time))
            conn.commit()
            time.sleep(5)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
